# ===========================================
# MOCK NPCI – Development Profile
# ===========================================
# SPRING_PROFILES_ACTIVE=dev,ssl
# ===========================================

logging:
  level:
    root: INFO
    com.hitachi: DEBUG
